### ISSUE TITLE
Failed syncs don't break CI

### ISSUE THREAD

**Issue by rbren** [reactiveops/charts#626] opened 2021-11-29 21:49 UTC
**Describe the bug**
This build should have broken: https://app.circleci.com/pipelines/github/FairwindsOps/charts/3054/workflows/95c430d7-ce37-468e-b14a-13add621ab82/jobs/16575?invite=true#step-103-58

**Comment by sudermanjr** [comment] 2021-11-29 21:54
Duplicate of https://github.com/FairwindsOps/charts/issues/289

**Closed as completed by sudermanjr** 2021-11-29 21:54 UTC
Labels: duplicate
